version: '3.6'
services:
  database:
    container_name: mysql_db
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root_pass'
      MYSQL_USER: 'user1'
      MYSQL_PASS: 'mypass1'
    volumes:
      - /usr/local/content/mysql:/var/lib/mysql
