version: '3'
services:
  web_app:
    container_name: web_app
    image: rkp201/web_db_connect:1.8
    networks:
      - metrics-nw
    ports:
      - 8080:8080
    restart:
      on-failure
  database:
    container_name: mysql_db
    restart: always
    image: mysql:8.0.25
    networks:
      - metrics-nw
    environment:
      MYSQL_ROOT_PASSWORD: 'root_pass'
networks:
  metrics-nw: {}