version: '3'
services:
  web_app:
    container_name: web_app
    image: httpd
    networks:
      - metrics-nw
    ports:
      - 80:80
    restart:
      on-failure
    volumes:
      - ./artifacts:/usr/artifacts
networks:
  metrics-nw: {}
